### ISSUE TITLE
calibration slider issue in Ubuntu 14.04

### ISSUE THREAD

**Issue by jvavrek** [zach-hartwig/ADAQAcquisition#10]
When attempting to calibrate, the slider and the dashed red line are offset, and dragging the red line does not update the ADC value shown in the box in the bottom right. Changing the display by adjusting the zoom, etc, tends to make the dashed red line disappear entirely. These issues were not present on the lab desktop computer.

**Comment by zach-hartwig** [comment]
At present, this appears to be an Ubuntu issue. I will close this but please reopen if you still have problems.
