### ISSUE TITLE
cannot save to .adaq.root in Ubuntu 14.04

### ISSUE THREAD

**Issue by jvavrek** [zach-hartwig/ADAQAcquisition#11]
The persistent storage option to save to a .adaq.root file produces only empty files (plus headers) in Ubuntu 14.04, when using the same saving procedures as on the Red Hat minos desktop lab computer.

**Comment by zach-hartwig** [comment]
Thanks for posting this issue.

This problem has been traced to new behavior introduced in ROOT version 5.34.32. The underlying functionality related to TGButton class (specifically the ::IsSelectedAndDisabled() method) seems to somehow have changed. The solution, at present, is to build on version 5.34.30. This has been tested and works perfectly. I will address this issue in the future; for now, I will close this issue.
