### ISSUE TITLE
Crash on long runs.

### ISSUE THREAD

**Issue by xmatter** [zach-hartwig/ADAQAcquisition#12]
During a long 16 hour run.  The program froze.  Here is the ouput from terminal.

ssnm2@mri-230-129:~$ ADAQAcquisition

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f3c6be149be in waitpid () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f3c6bd99f4e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f3c6ac38937 in TUnixSystem::StackTrace() () from /home/ssnm/root/lib/libCore.so
#3  0x00007f3c6ac3b223 in TUnixSystem::DispatchSignals(ESignals) () from /home/ssnm/root/lib/libCore.so
#4  <signal handler called>
#5  0x0000000000435e91 in AAAcquisitionManager::StartAcquisition() ()
#6  0x0000000000482346 in G__ADAQAcquisitionDict_794_0_2 (result7=0x2cbe660, funcname=<optimized out>, libp=<optimized out>, hash=<optimized out>) at build/ADAQAcquisitionDict.cc:3280
#7  0x00007f3c6a0d37cf in Cint::G__CallFunc::Execute(void*) () from /home/ssnm/root/lib/libCint.so
#8  0x00007f3c6abfa90c in TCint::CallFunc_Exec(void*, void*) const () from /home/ssnm/root/lib/libCore.so
#9  0x00007f3c6ab9b527 in TQConnection::ExecuteMethod() () from /home/ssnm/root/lib/libCore.so
#10 0x00007f3c6ab9deb8 in TQObject::Emit(char const*) () from /home/ssnm/root/lib/libCore.so
#11 0x00007f3c6b5ae048 in TGButton::EmitSignals(bool) () from /home/ssnm/root/lib/libGui.so
#12 0x00007f3c6b5aedf6 in TGButton::HandleButton(Event_t*) () from /home/ssnm/root/lib/libGui.so
#13 0x00007f3c6b5f624f in TGFrame::HandleEvent(Event_t*) () from /home/ssnm/root/lib/libGui.so
#14 0x00007f3c6b5c8a6b in TGClient::HandleEvent(Event_t*) () from /home/ssnm/root/lib/libGui.so
#15 0x00007f3c6b5c8bc5 in TGClient::ProcessOneEvent() () from /home/ssnm/root/lib/libGui.so
#16 0x00007f3c6b5c8c2d in TGClient::HandleInput() () from /home/ssnm/root/lib/libGui.so
#17 0x00007f3c6ac3b908 in TUnixSystem::DispatchOneEvent(bool) () from /home/ssnm/root/lib/libCore.so
#18 0x00007f3c6abbc846 in TSystem::InnerLoop() () from /home/ssnm/root/lib/libCore.so
#19 0x00007f3c6abbe524 in TSystem::Run() () from /home/ssnm/root/lib/libCore.so
#20 0x00007f3c6ab61caf in TApplication::Run(bool) () from /home/ssnm/root/lib/libCore.so
#21 0x000000000045f5d2 in main ()
===========================================================

The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x0000000000435e91 in AAAcquisitionManager::StartAcquisition() ()
===========================================================

**Comment by zach-hartwig** [comment]
Starting to work on closing out issues and fixing bugs. I will close this issue. If it is still a problem with newest version of the software, please reopen with more information. Thanks.
