### ISSUE TITLE
Using "Calibrate ADCs" button without connection

### ISSUE THREAD

**Issue by lkesler** [zach-hartwig/ADAQAcquisition#13]
Using "Calibrate ADCs" button without connection causes a seg fault. Shouldn't NEED to do this since it can't calibrate without a connection but still annoying to have to restart. Here's the text: 

*** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f15cdefc94a in waitpid () from /lib64/libc.so.6
#1  0x00007f15cde77a5b in do_system () from /lib64/libc.so.6
#2  0x00007f15d1878773 in TUnixSystem::StackTrace() () from /usr/local/root-6.06.00/lib/libCore.so
#3  0x00007f15d187a67c in TUnixSystem::DispatchSignals(ESignals) () from /usr/local/root-6.06.00/lib/libCore.so
#4  <signal handler called>
#5  0x0000000000435125 in AATabSlots::HandleConnectionTextButtons() ()
#6  0x00007f15d65d7027 in ?? ()
#7  0x0000000000000000 in ?? ()
===========================================================

The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x0000000000435125 in AATabSlots::HandleConnectionTextButtons() ()
#6  0x00007f15d65d7027 in ?? ()
#7  0x0000000000000000 in ?? ()
===========================================================

**Comment by zach-hartwig** [comment]
Thank you for submitting this bug. It has been patched in the HEAD of the master branch, to be released as part of v1.6.6.
