### ISSUE TITLE
Calibrating during acquisition saves data with calibration (not raw ADC)

### ISSUE THREAD

**Issue by lkesler** [zach-hartwig/ADAQAcquisition#14]
I did a quick calibration of my detector before acquiring data (in PSD DPP, but using list+waveform mode, saving energy data only). When I open the saved data files, they are not raw ADC, but with my original energy calibration. 

Discovered this on Fedora 21, with ADAQAcquisition 1.6.4, acquiring data with a DT590M digitizer and NaI detector. Zach verified with his own equipment (non- PSD DPP).

Sorry if I'm referring to things incorrectly Zach :)

**Comment by zach-hartwig** [comment]
Thanks for reporting this issue. I would call this more of a "feature" than a "bug" as it's a question of what the user expects to be written to the ADAQ file. The user could be given a choice (i.e. save calibrated or uncalibrated) but for now, I agree with your assessment that saving uncalibrated energy data to the ADAQ file is far more useful and the right "default" behavior.

This fix is now in the HEAD of the master branch, to be released in v1.6.6

Also, cool picture!
