### ISSUE TITLE
Bug: attempting to edit TCanvas display induces segfaults

### ISSUE THREAD

**Issue by jvavrek** [zach-hartwig/ADAQAcquisition#30]
While some user actions such as SetLogy() are permissible, attempting to e.g. resize the TCanvas during acquisition will cause a segfault. Is it possible just to "block" such an attempt?

**Comment by zach-hartwig** [comment]
Jayson,

This should be possible. I suspect that actions involving the TPad object on which the TCanvas object sits are valid (e.g. TStyle::SetLogy()) but that graphical actions directly involving the TCanvas object delete the underlying object pointer "outside" of ADAQAcquisition code. Thus, a segfault is caused when ADAQAcquisition attempts to use the TCanvas object pointer, which it think is still around.

There is a TPad::SetEditable(Bool_t) method that seems like it should do the trick (TCanvas inherits from TPad). I don't think ADAQAcquisition requires the user to interact with the TCanvas at any point (unlike ADAQAnalysis) so setting this flag either all the time or during acquisition should work. 

I'm away for 2 weeks but can try this on my return. If you want to give it a go, you can try modifying the source code and letting me know. You could even edit it properly and then send a pull request.
