### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by xmatter** [zach-hartwig/ADAQAcquisition#4]
I get the following error when compiling about no member named GetFileComment and SetFileComment.

ssnm2@mri-230-129:~/ADAQAcquisition$ make
-e 
Building object file 'build/AAAcquisitionManager.o' ...
clang++ -O2 -Wall -fPIC -pthread -m64 -I/home/ssnm/root/include -ferror-limit=5 -w -I/home/ssnm2/ADAQAcquisition/include -I/home/ssnm2/ADAQ//include -std=c++0x -c -o build/AAAcquisitionManager.o src/AAAcquisitionManager.cc
In file included from src/AAAcquisitionManager.cc:21:
/home/ssnm2/ADAQAcquisition/include/AAAcquisitionManager.hh:93:59: error: no
      member named 'GetFileComment' in 'ADAQReadoutManager'
  TString GetADAQFileComment() {return TheReadoutManager->GetFileComment();}
                                       ~~~~~~~~~~~~~~~~~  ^
/home/ssnm2/ADAQAcquisition/include/AAAcquisitionManager.hh:94:60: error: no
      member named 'SetFileComment' in 'ADAQReadoutManager'
  void SetADAQFileComment(TString AFC) {TheReadoutManager->SetFileComment(AFC);}
                                        ~~~~~~~~~~~~~~~~~  ^
2 errors generated.
make: *** [build/AAAcquisitionManager.o] Error 1

**Comment by xmatter** [comment]
Reinstalled ADAQ and ADAQAcquisition and it compiled......

**Comment by zach-hartwig** [comment]
These are the best kinds of issues for me to resolve! :) Good detective work.
