### ISSUE TITLE
Compiling ASIMReadout on mac

### ISSUE THREAD

**Issue by xmatter** [zach-hartwig/ADAQAcquisition#9]
If you need to compile ASIMReadout on Mac OSX then you must change the ASIMReadoutManager.cc to:
#include unistd.h
instead of 
#include sys/unistd.h

**Comment by zach-hartwig** [comment]
Hi,

Thanks for reporting this. It appears that  unistd.h will work on Linux as well as MacOS. unistd.h can be thought of as a symbolic link that points to the right /some/directory/unistd.h file so using "unistd.h", as you point out, is the correct, more general way to do this. I have pushed this change to the HEAD of the master branch in the ADAQ repo. It will be included in the next tagged version.

Additionally, I will be acquiring a Mac later this week to use in ADAQ development so I hope that you will see greater MacOS compatibility in the near future!
